name: test pipeline

on: [ push ]

jobs:
  build:
    name: pipeline test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test-environment
          environment-file: env.yml
          python-version: 3.6
          channels: bioconda,default,anaconda,conda-forge
          allow-softlinks: true
          channel-priority: 'flexible'
          show-channel-urls: true
          use-only-tar-bz2: true
          auto-update-conda: true
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show

      - name: Get mosdepth
        run: |
          wget https://github.com/brentp/mosdepth/releases/download/v0.3.1/mosdepth
          chmod +x mosdepth
          mv mosdepth /usr/share/miniconda/envs/test-environment/bin

      - name: Prep test data 
        run: |
          for FQ in data/*fastq; do cat $FQ | gzip > ${FQ}.gz; done

      - name: index bowtie2
        run: |
          bowtie2-build ref/Bavtpat1_complete.fa ref/Bavtpat1_complete.fa

      - name: Test pipeline
        run: |
          cd codes
          snakemake -s pipeline.smk -p -j 12 --config PROJECTPATH=$(dirname $(pwd))
